$:.unshift(File.join(File.dirname(__FILE__), 'src'))

require 'rake'
require 'rake/testtask'

Rake::TestTask.new('run_tests') do |test|
  test.pattern = './test/guess_game_test'
  test.verbose = true
  test.warning = true
end

task :run do
  ruby "play_game.rb"
end

task :default => [:run_tests]
